### ISSUE TITLE
Hiding Table Columns for different screen sizes.

### ISSUE THREAD

**Issue by akeshthemesh** [311labs/swam#6]
We are trying to figure out how to hide table columns when the screen size changes.  Is this possible?  For example if we have 4 table columns on the large screen we would like to only show 2 columns on the mobile screen.

**Comment by istarnes** [comment]
This can be done with bootstrap 5 classes.  In your column definition just add a classes parameter using bootstrap 5 visibility classes.  Remember to use table-cell instead of block.  So for example to hide a column in every display smaller then large you can do "d-none d-lg-table-cell".
https://getbootstrap.com/docs/5.0/utilities/display/

**Comment by akeshthemesh** [comment]
Ok, I see that now.  Thank you.
